// Attacker IPs (Table)
Syslog
| where SyslogMessage contains "whoami"
    or SyslogMessage contains "id"
    or SyslogMessage contains "/etc/passwd"
    or SyslogMessage contains "find /"
    or SyslogMessage contains "-perm"
| extend AttackerIP = extract(@"\b\d{1,3}(\.\d{1,3}){3}\b", 0, SyslogMessage)
| where isnotempty(AttackerIP)
| summarize Attempts = count() by AttackerIP
| order by Attempts desc


//  Attack Attempts Over Time (Line Chart)
Syslog
| where SyslogMessage contains "whoami"
    or SyslogMessage contains "id"
    or SyslogMessage contains "/etc/passwd"
    or SyslogMessage contains "find /"
    or SyslogMessage contains "-perm"
| summarize AttackCount = count() by bin(TimeGenerated, 5m)
| order by TimeGenerated asc
